name: Auto Pull Request Workflow

on:
  push:
    branches:
      - 'feature/**'
      - dev
      - hom
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout usando PAT
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      # 2️⃣ Determinar branch alvo
      - name: Determine target branch
        id: target
        run: |
          CURRENT_BRANCH=$(echo $GITHUB_REF | sed 's|refs/heads/||')
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV

          if [[ "$CURRENT_BRANCH" == feature/* ]]; then
            TARGET_BRANCH="dev"
          elif [[ "$CURRENT_BRANCH" == "dev" ]]; then
            TARGET_BRANCH="hom"
          elif [[ "$CURRENT_BRANCH" == "hom" ]]; then
            TARGET_BRANCH="main"
          else
            TARGET_BRANCH=""
          fi

          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV

      # 3️⃣ Criar Pull Request usando o mesmo PAT
      - name: Create Pull Request
        if: env.TARGET_BRANCH != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: ${{ env.CURRENT_BRANCH }}
          base: ${{ env.TARGET_BRANCH }}
          title: "Pull Request: ${{ env.CURRENT_BRANCH }} → ${{ env.TARGET_BRANCH }}"
          body: "Este PR foi gerado automaticamente pelo workflow. Revise e faça o merge manualmente."
          draft: false
